### ISSUE TITLE
Error running container

### ISSUE THREAD

**Issue by apastel** [lizard43/OWF#1]
I get this error when attempting to run the command in the README. Sorry, I'm a beginner with docker. Any advice?

```
$ sudo docker run -d -p 8080:8080 8443:8443 roadster/owf
Unable to find image '8443:8443' locally
docker: Error response from daemon: pull access denied for 8443, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by lizard43** [comment]
I see that my README was in error. Sorry.

You need another "-p" in front of your second port assignment
8443:8443

sudo docker run -d -p 8080:8080 -p 8443:8443 roadster/owf




On Nov 4, 2017 2:08 PM, "Alex Pastel" <notifications@github.com> wrote:

I get this error when attempting to run the command in the README. Sorry,
I'm a beginner with docker. Any advice?

$ sudo docker run -d -p 8080:8080 8443:8443 roadster/owf
Unable to find image '8443:8443' locally
docker: Error response from daemon: pull access denied for 8443,
repository does not exist or may require 'docker login'.
See 'docker run --help'.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lizard43/OWF/issues/1>, or mute the thread
